export const de = {
  translation: {
    enterStock: 'Aktiensymbol Eingeben',
    search: 'Suchen',
    recommendation: 'Empfehlung',
    stockAnalysis: 'Aktienanalyse',
    stockNews: 'Aktiennachrichten',
    news: 'Nachrichten',
    login: 'Anmeldung',
    language: 'Sprache',
    english: 'Englisch',
    greek: 'Griechisch',
    german: 'Deutsch',
    spanish: 'Spanisch',
    stockSymbolValidation: 'Das Aktiensymbol muss genau 4 Buchstaben haben',
    forex: 'Forex',
    crypto: 'Kryptowährungen',
    freeCashFlow: 'Free Cash Flow',
    incomeStatement: 'Income Statement',
    balanceSheet: 'Balance',
    metrics: 'Metrics',
  },
};
