export const en = {
  translation: {
    enterStock: 'Enter Stock',
    search: 'Search',
    recommendation: 'Recommendation',
    stockAnalysis: 'Stock Analysis',
    stockNews: 'Stock News',
    news: 'News',
    login: 'Login',
    language: 'Language',
    english: 'English',
    greek: 'Greek',
    german: 'German',
    spanish: 'Spanish',
    stockSymbolValidation: 'Stock symbol must be exactly 4 letters',
    forex: 'Forex',
    crypto: 'Crypto',
    dashboard: 'Dashboard',
    analystsRecommendations: 'Analysts Recommendations',
    providedByFinnhub: 'Provided By Finnhub',
  },
};
