export const fr = {
  translation: {
    enterStock: 'Entrer le symbole boursier',
    search: 'Rechercher',
    recommendation: 'Recommandation',
    stockAnalysis: 'Analyse des actions',
    stockNews: 'Actualités boursières',
    news: 'Actualités',
    login: 'Connexion',
    language: 'Langue',
    english: 'Anglais',
    greek: 'Grec',
    german: 'Allemand',
    spanish: 'Espagnol',
    stockSymbolValidation: 'Le symbole boursier doit comporter exactement 4 lettres',
    general: 'General',
    forex: 'Forex',
    crypto: 'Crypto-monnaie',
    dashboard: 'Tableau de bord',
    analystsRecommendations: 'Recommandations des analystes',
    providedByFinnhub: 'Fournie par Finnhub',
    freeCashFlow: 'Free Cash Flow',
    incomeStatement: 'Income Statement',
    balanceSheet: 'Balance',
    metrics: 'Metrics',
    category: 'Category',
    recommendations: 'Recommendations',
    welcome: 'Welcome'
  },
};
