export const gr = {
  translation: {
    enterStock: 'Εισαγωγή Συμβόλου Μετοχής',
    search: 'Αναζήτηση',
    recommendation: 'Σύσταση',
    stockAnalysis: 'Ανάλυση Μετοχών',
    stockNews: 'Νέα Μετοχών',
    news: 'Νέα',
    login: 'Σύνδεση',
    language: 'Γλώσσα',
    english: 'Αγγλικά',
    greek: 'Ελληνικά',
    german: 'Γερμανικά',
    spanish: 'Ισπανικά',
    stockSymbolValidation: 'Το σύμβολο μετοχής πρέπει να αποτελείται από ακριβώς 4 γράμματα',
    forex: 'Forex',
    crypto: 'Κρυπτονομίσματα',
    dashboard: 'Πίνακας Ελέγχου',
    analystsRecommendations: 'Συστάσεις Αναλυτών',
    providedByFinnhub: 'Παρέχεται από την Finnhub',
    freeCashFlow: 'Free Cash Flow',
    incomeStatement: 'Income Statement',
    balanceSheet: 'Balance'
  },
};
