export const sp = {
  translation: {
    enterStock: 'Ingresar Símbolo de Acciones',
    search: 'Buscar',
    recommendation: 'Recomendación',
    stockAnalysis: 'Análisis de Acciones',
    stockNews: 'Noticias de Acciones',
    news: 'Noticias',
    login: 'Iniciar Sesión',
    language: 'Idioma',
    english: 'Inglés',
    greek: 'Griego',
    german: 'Alemán',
    spanish: 'Español',
    stockSymbolValidation: 'El símbolo de las acciones debe tener exactamente 4 letras',
    forex: 'Forex',
    crypto: 'Criptomonedas',
    dashboard: 'Panel de Control',
    analystsRecommendations: 'Recomendaciones de Analistas',
    providedByFinnhub: 'Proporcionado por Finnhub',
    freeCashFlow: 'Free Cash Flow',
    incomeStatement: 'Income Statement',
    balanceSheet: 'Balance',
    metrics: 'Metrics',
  },
};
